# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

 buildGoPackage rec {
  name = "consulmux-unstable-${version}";
  version = "2018-08-12";
  rev = "b7afbf660302cee30d427a3e82ad40227329ea69";

   goPackagePath = "github.com/erincandescent/consulmux";

   src = fetchgit {
    inherit rev;
    url = "https://github.com/erincandescent/consulmux";
    sha256 = "1ll50apl8z9rqdqqqgldq40l8j26fkjgm10wgzd1nhbpf5v1a0xs";
  };

   goDeps = ./deps.nix;

   # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
