# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/coreos/go-systemd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/go-systemd";
      rev = "88bfeed483d372fa1298dd859662e4b9a13d68cb";
      sha256 = "03ga12dglxkia5jn5n1agjb3nlz2pjjywqndgzfbxzrb7gjkq4vc";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/consul";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/consul";
      rev = "e305443db4ba8295510faf2402e584650efeb3f8";
      sha256 = "1qb1wab3imjpj09z3kngr01xxz5h0fklavkjpxc1sc8h7ib924jk";
    };
  }
]
